import {fetchRemote,getPrices} from './remote.js';
import {getOfficialEconomics} from './economic-calendar.js';
const cache=new Map();
async function cached(key,ttl,fn){const hit=cache.get(key);if(hit&&Date.now()-hit.at<ttl)return hit.value;const value=await fn();if(cache.size>250)cache.delete(cache.keys().next().value);cache.set(key,{value,at:Date.now()});return value;}
function symbol(s){if(typeof s!=='string'||!/^[A-Za-z0-9.^=\-]{1,30}$/.test(s))throw Error('Invalid symbol');return s;}
async function json(url){const r=await fetchRemote(url);if(r.getResponseCode()!==200)throw Error('Source unavailable');return JSON.parse(r.getContentText());}
export async function getHistory(s){s=symbol(s);return cached('history:'+s,43200000,async()=>{const r=await json('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(s)+'?interval=1d&range=1y');const d=r.chart?.result?.[0];if(!d)throw Error('No history');const points=(d.timestamp||[]).map((t,i)=>({d:new Date(t*1000).toISOString().slice(0,10),p:d.indicators.quote[0].close[i]})).filter(x=>Number.isFinite(x.p));return {ok:true,symbol:s,currency:d.meta.currency,points,source:'Yahoo Finance',at:Date.now()};});}
function list(value,max=30){if(!Array.isArray(value)||value.length>max)throw Error('Invalid list');return value.map(x=>({...x,symbol:symbol(x.symbol)}));}
export async function getCompanyQuotes(value){const l=list(value,40);return cached('quotes:'+JSON.stringify(l),900000,async()=>{const quotes=await getPrices(l.map(x=>x.symbol).join(','));return {ok:true,quotes:Object.fromEntries(l.filter(x=>!quotes[x.symbol]?.error).map(x=>[x.key,{...quotes[x.symbol],symbol:x.symbol}]))};});}
export async function getNews(value){const l=list(value).slice(0,8);return cached('news:'+JSON.stringify(l),900000,async()=>{const items=[],seen=new Set();let successes=0;for(let i=0;i<l.length;i+=4)await Promise.all(l.slice(i,i+4).map(async x=>{try{const r=await json('https://query1.finance.yahoo.com/v1/finance/search?q='+encodeURIComponent(x.symbol)+'&quotesCount=0&newsCount=5');successes++;for(const n of r.news||[]){if(!n.link?.startsWith('https:')||seen.has(n.link))continue;seen.add(n.link);items.push({a:x.name,via:x.via||'',t:n.title,url:n.link,source:n.publisher,date:n.providerPublishTime?new Date(n.providerPublishTime*1000).toISOString():null});}}catch{}}));return {ok:successes>0||!l.length,items:items.sort((a,b)=>(b.date||'').localeCompare(a.date||'')),error:successes?null:'الأخبار غير متاحة من المصدر'};});}
export async function getCalendar(value,options={}){
 const l=list(value,60),key=typeof Deno!=='undefined'?Deno.env.get('FMP_API_KEY'):null;
 return cached('calendar:'+JSON.stringify([l,options]),86400000,async()=>{
  const from=new Date().toISOString().slice(0,10),to=new Date(Date.now()+180*86400000).toISOString().slice(0,10),items=[],unavailable=[];
  const official=await getOfficialEconomics(from,to);items.push(...official.items);
  if(key){
   try{const data=await json('https://financialmodelingprep.com/stable/earnings-calendar?from='+from+'&to='+to+'&apikey='+encodeURIComponent(key));if(!Array.isArray(data))throw Error();for(const e of data){const a=l.find(x=>x.symbol===e.symbol);if(a)items.push({c:'earn',d:e.date,t:'نتائج '+a.name,s:'FMP · موعد معلن قابل للتغيير',src:'FMP',asset:a.asset||a.name});}}catch{unavailable.push('تقويم الأرباح غير متاح باشتراك المصدر الحالي');}
   try{const data=await json('https://financialmodelingprep.com/stable/economic-calendar?from='+from+'&to='+to+'&apikey='+encodeURIComponent(key));if(!Array.isArray(data))throw Error();const countries=new Set((options.countries||[]).slice(0,100));for(const e of data)if(countries.has(e.country)&&/high/i.test(e.impact||'')&&/interest|rate|inflation|cpi/i.test(e.event||''))items.push({c:'macro',d:String(e.date).slice(0,10),t:e.event,s:e.country+' · FMP',src:'FMP'});}catch{unavailable.push('التقويم الاقتصادي غير متاح باشتراك المصدر الحالي');}
  }else unavailable.push('تقويم نتائج الشركات يحتاج مفتاح FMP على الخادم');
  const direct=l.filter(x=>!x.component).slice(0,12);let divSuccess=0;
  for(let i=0;i<direct.length;i+=4)await Promise.all(direct.slice(i,i+4).map(async a=>{try{const r=await json('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(a.symbol)+'?interval=1mo&range=2y&events=div');const dividends=Object.values(r.chart?.result?.[0]?.events?.dividends||{}).map(x=>x.date*1000).sort((a,b)=>a-b);divSuccess++;if(dividends.length<3)return;const intervals=dividends.slice(1).map((d,i)=>(d-dividends[i])/86400000).sort((a,b)=>a-b),gap=intervals[Math.floor(intervals.length/2)];if(gap<20||gap>380||intervals.some(x=>Math.abs(x-gap)>gap*.25))return;const next=dividends.at(-1)+gap*86400000;if(next<Date.now()||next>Date.now()+180*86400000)return;items.push({c:'div',d:new Date(next).toISOString().slice(0,10),t:'توزيع '+a.name+' — تقديري',s:'تقدير من انتظام التوزيعات السابقة؛ ليس إعلانًا مؤكدًا',src:'Yahoo',asset:a.name});}catch{}}));
  if(direct.length&&!divSuccess)unavailable.push('سجل التوزيعات غير متاح');
  if(options.msci){try{const rows=await cached('msci',30*86400000,async()=>{const r=await fetchRemote('https://www.msci.com/eqb/pressreleases/archive/ir_dates.csv');if(r.getResponseCode()!==200)throw Error();return r.getContentText();});let count=0;for(const row of rows.split(/\r?\n/)){const cells=row.match(/("[^"]*"|[^,]+)(,|$)/g)||[];const dates=cells.map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').trim()).filter(x=>/\d/.test(x)&&/[\/-]/.test(x)).map(x=>new Date(x)).filter(x=>Number.isFinite(+x));dates.forEach((d,i)=>{const date=d.toISOString().slice(0,10);if(date>=from&&date<=to){items.push({c:'idx',d:date,t:i?'سريان مراجعة MSCI':'إعلان مراجعة MSCI',s:'الجدول الرسمي لمراجعات المؤشرات',src:'MSCI'});count++;}});}if(!count)unavailable.push('لا مواعيد MSCI مقروءة في الفترة القادمة');}catch{unavailable.push('ملف مواعيد MSCI غير متاح من المصدر');}}
  const unique=[...new Map(items.map(e=>[e.d+'|'+e.t,e])).values()];return {ok:true,items:unique,unavailable,sources:official.status,at:Date.now()};
 });
}
export async function getMarketStatus(s){s=symbol(s);const d=await json('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(s)+'?interval=1d&range=1d');const m=d.chart?.result?.[0]?.meta,p=m?.currentTradingPeriod?.regular,now=Date.now()/1000;return {ok:!!p,open:p?now>=p.start&&now<=p.end:null,timestamp:m?.regularMarketTime};}
