import test from 'node:test';
import assert from 'node:assert/strict';
import {createAuthenticatedRequests} from '../src/auth-requests.js';
import {createAPI} from '../src/api.js';
import {emptyPortfolio} from '../src/state.js';
const session=(token='old',expires_at=Date.now()/1000+3600)=>({access_token:token,expires_at,user:{id:'owner'}});
function fixture(){let current=session(),refreshes=0;const client={auth:{getSession:async()=>({data:{session:current}}),refreshSession:async()=>{refreshes++;await new Promise(r=>setTimeout(r,5));current=session('new');return {data:{session:current}};}}};return {client,setSession:s=>current=s,refreshes:()=>refreshes};}
test('concurrent RPC and Edge 401 responses share a refresh and use the new bearer',async()=>{const f=fixture();let rpc=0,edge=0;f.client.rpc=async()=>++rpc===1?{status:401,error:{code:'PGRST301',message:'JWT expired'}}:{data:'loaded'};f.client.functions={invoke:async(_,options)=>++edge===1?{error:{context:{status:401}}}:{data:options.headers.Authorization}};const request=createAuthenticatedRequests(f.client);const [a,b]=await Promise.all([request.rpc('load_portfolio'),request.invoke('getPrices',[])]);assert.equal(f.refreshes(),1);assert.equal(a.data,'loaded');assert.equal(b.data,'Bearer new');});
test('refreshes a nearly expired session before sending a request',async()=>{const f=fixture();f.setSession(session('old',Date.now()/1000+20));f.client.functions={invoke:async(_,o)=>({data:o.headers.Authorization})};assert.equal((await createAuthenticatedRequests(f.client).invoke('getPrices',[])).data,'Bearer new');assert.equal(f.refreshes(),1);});
test('invalid refresh prompts login without replaying a request',async()=>{const f=fixture();let calls=0,prompts=0;f.client.rpc=async()=>{calls++;return {status:401,error:{message:'JWT expired'}}};f.client.auth.refreshSession=async()=>({data:{session:null},error:{status:400}});const r=createAuthenticatedRequests(f.client,{onAuthRequired:()=>prompts++});await assert.rejects(r.rpc('save_portfolio'),e=>e.code==='SESSION_EXPIRED');assert.equal(calls,1);assert.equal(prompts,1);assert(r.requiresLogin());});
test('does not retry network failures, 500s or conflicts and caps auth replay at once',async()=>{for(const response of [{status:500,error:{message:'server unavailable'}},{error:{message:'PORTFOLIO_CONFLICT'}},{error:{message:'Failed to fetch'}},{status:401,error:{message:'JWT expired'}}]){const f=fixture();let n=0;f.client.rpc=async()=>{n++;return response};const r=createAuthenticatedRequests(f.client);if(response.status===401){await assert.rejects(r.rpc('save_portfolio'),e=>e.code==='SESSION_EXPIRED');assert.equal(n,2);assert.equal(f.refreshes(),1);}else{assert.equal(await r.rpc('save_portfolio'),response);assert.equal(n,1);assert.equal(f.refreshes(),0);}}});
test('does not replay a save under a different refreshed user',async()=>{const f=fixture();let n=0;f.client.rpc=async()=>{n++;return {status:401,error:{message:'JWT expired'}}};f.client.auth.refreshSession=async()=>({data:{session:{...session('new'),user:{id:'other'}}}});await assert.rejects(createAuthenticatedRequests(f.client).rpc('save_portfolio'),e=>e.code==='SESSION_EXPIRED');assert.equal(n,1);});
test('auth rejection before a save is retried once with the same version and payload',async()=>{const f=fixture();let saves=0;const args=[];f.client.rpc=async(name,arg)=>{if(name==='load_portfolio')return {data:{version:8,data:emptyPortfolio()}};saves++;args.push(arg);return saves===1?{status:401,error:{message:'JWT expired'}}:{data:{version:9,data:arg.next_data}};};const api=createAPI(f.client);await api.call('loadAll');await api.call('saveSetting','view','cc');assert.equal(saves,2);assert.deepEqual(args[0],args[1]);assert.equal(api.snapshot().settings.view,'cc');assert.equal(api.isBlocked(),false);});
test('failed reload preserves the last loaded portfolio state',async()=>{let fail=false;const f=fixture(),data=emptyPortfolio();data.settings.goal='keep';f.client.rpc=async()=>fail?{status:500,error:Error('offline')}:{data:{version:8,data}};const api=createAPI(f.client);await api.call('loadAll');fail=true;await assert.rejects(api.call('loadAll'),/offline/);assert.equal(api.snapshot().settings.goal,'keep');});
