import test from 'node:test';
import assert from 'node:assert/strict';
import {parseIssuerDividends,normalizeYahooDividends,projectDistributions,issuerPageURL} from '../supabase/functions/portfolio-market/dividend-sources.js';
// Same public component shape as the issuer's ISWD distribution table.
const table={exDate:{value:[20260521,20251113,20250515,20241114]},payableDate:{value:[20260529,20251126,20250529,20241127]},recordDate:{value:[20260522,20251114,20250516,20241115]},totalDistribution:{value:['0.3174','0.3308','0.3092','0.3366'],prefix:['USD ','USD ','USD ','USD ']}};
const page='<walrus componentprops="'+JSON.stringify({containersByNameMap:{distributions:{subContainersByNameMap:{table:{dataPointsByNameMap:table}}}}}).replaceAll('"','&quot;')+'">';
test('issuer records preserve explicit distribution currency and distinguish payment from ex date',()=>{const h=parseIssuerDividends(page);assert.equal(h.length,4);assert.equal(h.at(-1).currency,'USD');assert.equal(h.at(-1).perShare,.3174);assert.equal(h.at(-1).exDate,'2026-05-21');assert.equal(h.at(-1).paymentDate,'2026-05-29');const r=projectDistributions(h,'2026-10-05');assert.equal(r.frequency,2);assert.equal(r.upcoming.length,2);assert.equal(r.upcoming[0].perShare,.3308);assert.equal(r.upcoming[0].status,'estimated');assert.equal(r.upcoming[0].dateKind,'payment');});
test('listing currency is never used as dividend currency, including GBp priced funds',()=>{const h=normalizeYahooDividends({meta:{currency:'GBp'},events:{dividends:{a:{date:1747267200,amount:.31},b:{date:1762992000,amount:.33},c:{date:1779321600,amount:.32}}}});assert(h.every(e=>e.currency===null&&e.paymentDate===null));const r=projectDistributions(h,'2026-10-05');assert(r.upcoming.length);assert(r.upcoming.every(e=>e.currency===null&&e.dateKind==='ex'));});
test('announced payment is kept once and has priority over a projected installment',()=>{const h=parseIssuerDividends(page);h.push({exDate:'2026-11-19',paymentDate:'2026-11-27',currency:'USD',perShare:.35});const r=projectDistributions(h,'2026-10-05');assert.equal(r.upcoming.filter(e=>e.date.startsWith('2026-11')).length,1);assert.equal(r.upcoming[0].status,'announced');assert.equal(r.upcoming[0].perShare,.35);});
test('insufficient, stale and irregular histories do not produce recurring forecasts',()=>{const h=parseIssuerDividends(page);assert.equal(projectDistributions(h.slice(-2),'2026-10-05').upcoming.length,0);assert.equal(projectDistributions(h,'2028-10-05').upcoming.length,0);assert.equal(projectDistributions([...h.slice(0,2),{...h[2],exDate:'2026-04-01'},h[3]],'2026-10-05').upcoming.length,0);assert.deepEqual(parseIssuerDividends('<html>source failed</html>'),[]);});
test('issuer URL resolver accepts only official product pages and strips CSV download suffixes',()=>{assert.equal(issuerPageURL('https://www.ishares.com/uk/individual/en/products/251394/fund/123.ajax?fileType=csv'),'https://www.ishares.com/uk/individual/en/products/251394/fund');for(const url of ['http://www.ishares.com/uk/products/123/f','https://www.ishares.com.evil.test/products/123/f','https://x@www.ishares.com/products/123/f','https://www.ishares.com:8080/products/123/f'])assert.equal(issuerPageURL(url),null);});
