import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const context={Intl,Date};vm.runInNewContext(fs.readFileSync('public/command-center/market-pulse.js','utf8'),context);const p=context.TharwaPulse;
test('all supported countries are requested beyond the top ten; shared currencies only once',()=>{const countries=['US','CN','HK','JP','GB','CA','DE','FR','NL','CH','AU','IN','TW','KR','SA'];const rows=p.requests(countries);assert.equal(rows.filter(r=>r.key.startsWith('market:')).length,15);assert.equal(rows.filter(r=>r.key==='fx:EUR').length,1);assert.ok(rows.some(r=>r.key==='market:SA'));assert.ok(rows.some(r=>r.key==='fx:SAR'));});
test('FX movement is inverted and cross-converted into SAR, not the USD/foreign quote direction',()=>{const q={'fx:SAR':{price:3.75,changePct:0,timestamp:100},'fx:JPY':{price:150,changePct:2,timestamp:90}};const x=p.fx('JPY',q);assert.equal(x.rate,.025);assert.ok(Math.abs(x.changePct-(-1.96078431372549))<1e-8);assert.equal(x.timestamp,90);assert.equal(p.fx('SAR',q).changePct,0);assert.equal(p.fx('ZZZ',q),null);});
test('missing FX daily change is never displayed as flat',()=>{const x=p.fx('EUR',{'fx:SAR':{price:3.75,changePct:0},'fx:EUR':{price:.9}});assert.equal(x.changePct,null);});
test('calendar day labels follow Riyadh midnight and never show hours',()=>{assert.equal(p.dayLabel('2026-10-09',Date.parse('2026-10-08T21:01:00Z')),'اليوم');assert.equal(p.dayLabel('2026-10-10',Date.parse('2026-10-08T21:01:00Z')),'غدًا');assert.equal(p.dayLabel('2026-10-11',Date.parse('2026-10-08T21:01:00Z')),'بعد 2 يوم');});
test('session times are checked against current time, not a cached boolean',()=>{const q={marketOpen:true,session:{start:100,end:200}};assert.match(p.session(q,150000),/مفتوح/);assert.match(p.session(q,250000),/مغلق/);assert.match(p.session(q,50000),/يفتح/);assert.match(p.session({marketOpen:true}),/غير متاحة/);});

import {getGlobeQuotes,getMarketBriefing} from '../supabase/functions/portfolio-market/command-sources.js';
test('globe transport retains session and quote time, flags missing symbols and caches responses',async()=>{const previous=globalThis.fetch;let calls=0;globalThis.fetch=async url=>{calls++;if(String(url).includes('BADPULSE'))return new Response('{}',{status:503});return new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:102,chartPreviousClose:100,regularMarketTime:12345,currency:'USD',currentTradingPeriod:{regular:{start:100,end:200}}}}]}}));};try{const input=[{key:'market:US',symbol:'TESTPULSE'},{key:'market:ZZ',symbol:'BADPULSE'}];const r=await getGlobeQuotes(input);assert.equal(r.quotes['market:US'].changePct,2.0000000000000018);assert.equal(r.quotes['market:US'].session.end,200);assert.equal(r.quotes['market:US'].timestamp,12345);assert.deepEqual(r.unavailable,['market:ZZ']);await getGlobeQuotes(input);assert.equal(calls,2);await assert.rejects(getGlobeQuotes([{key:'bad',symbol:'https://bad.example'}]));}finally{globalThis.fetch=previous;}});
test('briefing preserves dated sources, removes old and unrelated items and deduplicates',async()=>{const previous=globalThis.fetch;const date=new Date().toUTCString();globalThis.fetch=async()=>new Response(`<rss><channel><item><title>Fed interest rates decision</title><link>https://www.federalreserve.gov/news.htm</link><pubDate>${date}</pubDate></item><item><title>Gold old news</title><link>https://example.com/old</link><pubDate>1 Jan 2020 00:00:00 GMT</pubDate></item><item><title>Sports final</title><link>https://example.com/sport</link><pubDate>${date}</pubDate></item></channel></rss>`);try{const r=await getMarketBriefing();assert.equal(r.items.length,1);assert.equal(r.items[0].scope,'macro');assert.ok(r.items[0].date);assert.equal(r.unavailable.length,0);}finally{globalThis.fetch=previous;}});
