import test from 'node:test';import assert from 'node:assert/strict';import {emptyPortfolio,mutatePortfolio} from '../src/state.js';import {createAPI} from '../src/api.js';import {readWorkbook,exportTransactions} from '../src/workbook.js';import ExcelJS from 'exceljs';import {parseIsharesCsv_} from '../supabase/functions/portfolio-market/providers.js';
const txn=(id,extra={})=>({id,date:'2026-09-30',assetType:'Stock',assetName:'TEST',action:'Buy',qty:2,price:50,fees:0,currency:'USD',rate:3.75,totalCostSAR:375,remarks:'',...extra});
test('linked transactions archive and restore atomically',()=>{let d=emptyPortfolio();d.txns=[txn(1,{linkedTxnId:2}),txn(2,{assetType:'Cash',action:'Withdrawal',linkedTxnId:1})];d=mutatePortfolio(d,'archiveDeletedTxns',[[d.txns[0]]]).data;assert.equal(d.txns.length,0);assert.equal(d.deletedTxns.length,2);d=mutatePortfolio(d,'restoreTxns',[[1]]).data;assert.equal(d.txns.length,2);assert.equal(d.deletedTxns.length,0);assert.equal(d.txns[0].linkedTxnId,2);});
test('bulk replacement guards missing rows and keeps backup',()=>{let d=emptyPortfolio();d.txns=[txn(1),txn(2)];const guard=mutatePortfolio(d,'syncTxns',[[txn(1)],{}]);assert.equal(guard.result.needsConfirm,true);const next=mutatePortfolio(d,'syncTxns',[[txn(1)],{force:true}]);assert.equal(next.data.backupTxns.length,2);assert.equal(next.data.deletedTxns.length,1);});
test('conflicting writes block subsequent saves',async()=>{let saves=0;const client={rpc:async(name)=>name==='load_portfolio'?{data:{version:8,data:emptyPortfolio()}}:(saves++,{error:new Error('PORTFOLIO_CONFLICT')})};const api=createAPI(client);await api.call('loadAll');await assert.rejects(api.call('addTxn',txn(1)),/CONFLICT/);await assert.rejects(api.call('addTxn',txn(2)),/متوقف/);assert.equal(saves,1);assert.deepEqual(api.snapshot().txns,[]);});
test('Excel preserves fractional IDs, amounts, linked ID and literal text',async()=>{const input=txn(1776880842377.3618,{linkedTxnId:1776880842379.5178,remarks:'=HYPERLINK("evil")',fees:0,totalCostSAR:-987.125});const bytes=await exportTransactions([input]);const wb=new ExcelJS.Workbook();await wb.xlsx.load(bytes);const s=wb.getWorksheet('Transactions');assert.equal(s.getCell('A2').value,String(input.id));assert.equal(s.getCell('M2').value,String(input.linkedTxnId));assert.equal(s.getCell('K2').value,input.totalCostSAR);assert.equal(s.getCell('L2').value,input.remarks);assert.equal(s.getCell('L2').type,ExcelJS.ValueType.String);});
test('headerless settings keep the first key and dates normalized',async()=>{const w=new ExcelJS.Workbook();w.addWorksheet('Settings').addRow(['retireGoal',2805000]);const s=w.addWorksheet('Transactions');const x=txn(1);s.addRow(Object.keys(x));s.addRow(Object.values({...x,date:new Date('2026-09-30T00:00:00Z')}));for(const n of ['Assets','Notes','OtherSources','Deletedtxns'])w.addWorksheet(n).addRow(['id']);const p=await readWorkbook(await w.xlsx.writeBuffer());assert.equal(p.settings.retireGoal,'2805000');assert.equal(p.txns[0].date,'2026-09-30');});
test('iShares holdings parser survives port from copied Markdown',()=>{const r=parseIsharesCsv_('Fund title\nTicker,Name,Sector,Asset Class,Market Value,Weight (%),Location\nMSFT,Microsoft,Information Technology,Equity,100,60,United States\nAAPL,Apple,Information Technology,Equity,100,40,United States',10);assert.equal(r.ok,true);assert.equal(r.top.length,2);});
test('FIFO preserves realized profit and remaining cost across sales and reentry',async()=>{
 const fs=await import('node:fs');const vm=await import('node:vm');const {parse}=await import('@babel/parser');const source=fs.readFileSync(new URL('../public/legacy/app.js',import.meta.url),'utf8');const ast=parse(source,{sourceType:'script'});const fn=ast.program.body.find(n=>n.type==='FunctionDeclaration'&&n.id.name==='calcFIFO');const context=vm.createContext({pN:Number});vm.runInContext(source.slice(fn.start,fn.end),context);
 const r=context.calcFIFO([txn(1,{qty:10,totalCostSAR:100,date:'2026-01-01'}),txn(2,{qty:10,totalCostSAR:200,date:'2026-02-01'}),txn(3,{qty:15,totalCostSAR:-450,action:'Sell',date:'2026-03-01'})]);assert.equal(r.netQty,5);assert.equal(r.avgCostSAR,20);assert.equal(r.realizedPnL,250);
 const exit=context.calcFIFO([txn(1,{qty:10,totalCostSAR:100,date:'2026-01-01'}),txn(2,{qty:10,totalCostSAR:-150,action:'Sell',date:'2026-02-01'}),txn(3,{qty:5,totalCostSAR:200,date:'2026-03-01'})]);assert.equal(exit.avgCostSAR,40);assert.equal(exit.repurchases.length,1);
});
test('quote contract matches original market UI and blocks unknown hosts',async()=>{
 const {getPrices,fetchRemote}=await import('../supabase/functions/portfolio-market/remote.js');const saved=globalThis.fetch;
 try{globalThis.fetch=async()=>new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:100,currency:'USD',chartPreviousClose:80,fiftyTwoWeekHigh:120,shortName:'Example'}}]}}),{status:200});const r=await getPrices('TEST');assert.equal(r.TEST.changePct,25);assert.equal(r.TEST.high52,120);await assert.rejects(fetchRemote('http://127.0.0.1/'),/غير مسموح/);await assert.rejects(fetchRemote('https://attacker.test/'),/غير مسموح/);}finally{globalThis.fetch=saved;}
});
