from pathlib import Path
r=Path(__file__).resolve().parents[1]
def patch(file,old,new):
 p=r/file;s=p.read_text()
 if s.count(old)!=1:raise SystemExit('FAIL '+file+' '+old[:90])
 p.write_text(s.replace(old,new,1));print('OK',file,old[:55])
patch('public/legacy/command-bridge.js','includeUnrealized,\n   XR:',"includeUnrealized,marketHidden:[...marketHidden].map(String),marketOrder:marketOrder.map(String),\n   XR:")
patch('scripts/cc/core.overrides.js','function build(){POS=S.POS;}',"function build(){POS=S.POS.filter(p=>assetVisible(p.n));}\nfunction assetVisible(n){return !(S.marketHidden||[]).includes(String(AS[n]?.id));}\nfunction visibleOther(o){return o.inc!==false&&(o.type!=='unrealized'||S.includeUnrealized);}")
patch('scripts/cc/core.overrides.js',"arr.splice(0,arr.length,...S[key]);", "arr.splice(0,arr.length,...(key==='OTHER'?S.OTHER.filter(visibleOther):S[key]));")
patch('scripts/cc/core.overrides.js','CTX=S.CTX;DELETED=S.deleted;POS=S.POS;baseCur=S.baseCur;','CTX=S.CTX;DELETED=S.deleted;build();baseCur=S.baseCur;')
patch('scripts/cc/core.overrides.js',"const changed=key=>force||baseCur!==old.baseCur||", "const changed=key=>force||baseCur!==old.baseCur||S.includeUnrealized!==old.includeUnrealized||JSON.stringify(S.marketHidden)!==JSON.stringify(old.marketHidden)||")
patch('scripts/cc/core.overrides.js',"Object.entries(AS).filter(([,p])=>['Stock','Gold'].includes(p.t))", "Object.entries(AS).filter(([n,p])=>assetVisible(n)&&['Stock','Gold'].includes(p.t))")
patch('scripts/cc/core.overrides.js',"Object.keys(AS).filter(k=>AS[k].yh).map(k=>[k,k])", "Object.keys(AS).filter(k=>AS[k].yh&&assetVisible(k)).map(k=>[k,k])")
patch('scripts/cc/core.overrides.js',"const list=NEWS.filter(n=>nwF==='all'||n.a===nwF);", "const list=NEWS.filter(n=>assetVisible(n.a)&&(nwF==='all'||n.a===nwF));")
patch('scripts/cc/core.overrides.js',"for(const fn of ['openAsset'", "for(const fn of ['openNews','openAsset'")
patch('scripts/cc/settings.overrides.js',"+OTHER.map((o,i)=>srow", "+S.OTHER.map((o,i)=>srow")
# Restore the reference dialog's exact information architecture, adapting only data availability.
reference=Path('/workspace/scratch/7ad016543a24/upload/odb-command-center (11).html').read_text()
a=reference.index('function openAsset(n){');b=reference.index('/* خريطة الدولة',a);fn=reference[a:b].strip()
fn=fn.replace("const p=POS.find(x=>x.n===n);if(!p)return;", "const asset=AS[n];if(!asset)return;const f=ENGINE.fifo(n),p=S.POS.find(x=>x.n===n)||{...asset,n,qty:0,val:0,cost:0,avg:0,pnl:0,realized:f.realized,sells:f.sells};")
fn=fn.replace('w=p.val/T.total*100','w=percent(p.val,T.total)')
fn=fn.replace("if(d&&p.t==='Stock'&&n!=='BYD')", "if(d&&p.t==='Stock'&&d.kind==='etf')")
fn=fn.replace('d.top.slice(0,6)', '(d.top||[]).slice(0,6)')
fn=fn.replace('class="row"><div class="nm"><div class="t" style="font-weight:500">${flag(cc)} ${ar}', 'class="row clk" onclick="openCompany(\'${k}\')"><div class="nm"><div class="t" style="font-weight:500">${flag(cc)} ${ar}')
fn=fn.replace('Object.entries(d.countries).slice(0,4)','Object.entries(d.countries||{}).sort((a,b)=>b[1]-a[1]).slice(0,4)')
fn=fn.replace('openHolo(`\n', 'openHolo(`<div class="asset-dialog">\n')
fn=fn.replace('${p.tv} · ${p.yh}', "${p.tv||''} · ${p.yh||''}")
fn=fn.replace("${p.chg>=0?'▲ +':'▼ '}${fmt(Math.abs(p.chg),2)}% اليوم", "${p.chg==null?'حركة اليوم غير متاحة':(p.chg>=0?'▲ +':'▼ ')+fmt(Math.abs(p.chg),2)+'% اليوم'}")
fn=fn.replace('≈ ${fmtC(toSAR(p.p,p.cur))}', "${p.p==null?'':'≈ '+fmtC(toSAR(p.p,p.cur))}")
fn=fn.replace("cell('القيمة الحالية',fmtC(p.val),'up')", "cell(p.hasPx?'القيمة الحالية':'القيمة بالتكلفة — السعر غير متاح',fmtC(p.val),'up')")
fn=fn.replace('fmt(p.pnl/p.cost*100,1)','fmt(percent(p.pnl,p.cost),1)')
fn=fn.replace("`${p.realized>=0?'+':'−'}${fmtC(p.realized)}`", "sgn(p.realized)")
fn=fn.replace('<div class="chartbox">${chart52(p)}</div>', '<div class="chartbox" id="assetHistory">${chart52(p)}</div>')
fn=fn.replace('<div class="bar2"><s style="left:${ap}%"></s><i style="left:${rp}%"></i></div>', '<div class="bar2">${p.hi>p.lo&&p.p!=null?`<s style="left:${ap}%"></s><i style="left:${Math.max(0,Math.min(100,rp))}%"></i>`:""}</div>')
fn=fn.replace('natFmt(t[4],p.cur)', "natFmt(t[4],t[8]?.currency||p.cur)")
fn=fn.replace('  </div>`);\n}', '  </div></div>`);if(p.yh&&!historyData[p.yh])loadHistory(n);\n}')
p=r/'scripts/cc/dialogs.overrides.js';s=p.read_text();a=s.index('function openAsset(n){');b=s.index('async function loadHistory',a);s=s[:a]+fn+'\n'+s[b:];p.write_text(s);print('OK reference asset dialog')
patch('scripts/cc/dialogs.overrides.js',"chart52(POS.find(p=>p.n===n)||{...a,n})", "chart52(S.POS.find(p=>p.n===n)||{...a,n})")
patch('scripts/cc/dialogs.overrides.js','Y(t[4]))','Y(movementQuotePrice(t,p.cur)))')
patch('scripts/cc/dialogs.overrides.js',"natFmt(t[4],p.cur)}</title>","natFmt(t[4],t[8]?.currency||p.cur)}</title>")
